spring:
  application:
    name: PCFSpringBootDemo
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    dbcp2:
      initial-size: 1
      max-total: 1
      remove-abandoned-on-borrow: true
      remove-abandoned-on-maintenance: true
endpoints:
  actuator:
    enabled: true
management:
  security:
    enabled: false